[package]
name = "ffi-attributes"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.80"
proc-macro2 = "1.0.30"
darling = "0.13.0"
quote = "1.0.10"
serde = { version = "1.0.130", features = ["derive"] }