[package]
name = "doublets"
version = "0.1.0"
edition = "2018"

[dependencies]
static_assertions = "0.1"
num-traits = "0.2"
smallvec = "1.7.0"
memmap2 = "0.5.0"
rand = "0.8.0"
libc = "0.1.0"
bumpalo = "3.8.0"

[profile.test]
