[package]
name = "doublets"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "0.1"
num-traits = "0.2"
memmap = "0.7.0"
rand = "0.8.0"
libc = "0.1.0"

[profile.test]
