[package]
name = "integration"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "test-mem"
path = "src/bins/test-mem.rs"

[dependencies]
doublets = { path = "../doublets" }
mem = { package = "platform-mem", version = "0.1.0-alpha.0" }