name: CD

on: [push]

env:
  NUGETTOKEN: ${{ secrets.NUGET_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SCRIPTS_BASE_URL: https://raw.githubusercontent.com/linksplatform/Scripts/master/MultiProjectRepository
  CARGO_TERM_COLOR: always

jobs:
  bench_rust_on_windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - name: Rustup nightly
        run: rustup toolchain install nightly
      - name: Bench
        run: |
          cd rust
          cargo +nightly test --release --package doublets --lib tests::sync::super_read -- --exact --nocapture
