name: releaseWorkflow

on:
  workflow_run:
    workflows: ["cppWorkflow", "csWorkflow", "rustWorkflow"]
    types:
      - completed


env:
  NUGETTOKEN: ${{ secrets.NUGET_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SCRIPTS_BASE_URL: https://raw.githubusercontent.com/linksplatform/Scripts/master/MultiProjectRepository

jobs:
  publiseRelease:
    runs-on: ubuntu-latest

    if: (needs.deployCpp.result == 'skipped' || needs.deployCs.result == 'skipped' && needs.deployRust.result == 'skipped') && !failure() && !cancelled()
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Publish release
        run: |
          export REPOSITORY_NAME=$(basename ${{ github.repository }})
          wget "$SCRIPTS_BASE_URL/publish-release.sh"
          bash ./publish-release.sh