name: RustWorkflow

on:
  push:
    branches: ["main"]
    paths:
      - 'rust/**'
      - '.github/workflows/rust.yml'

env:
  RUST_BACKTRACE: 1
  rust_stable: stable
  rust_nightly: nightly

defaults:
  run:
    shell: bash

jobs:

  pass:
    name: all passed
    runs-on: ubuntu-latest
    needs:
      - test
      - valgrind
    steps:
      - run: exit 0

  test:
    name: test doublets full
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust ${{ env.rust_nigthly }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_stable }}
          override: true
      - name: Install Rust Nightly
        run: rustup default nightly

      - name: test doublets
        run: cargo +nightly test --lib
        working-directory: rust

  valgrind:
    name: valgrind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust ${{ env.rust_nigthly }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_stable }}
          override: true
      - name: Install Rust Nightly
        run: rustup default nightly

      - uses: Swatinem/rust-cache@v1

      - name: Install Valgrind
        run: |
          sudo apt-get update -y
          sudo apt-get install -y valgrind

      - name: cargo build
        run: cargo +nightly build --bin test-mem
        working-directory: rust/integration

      - name: Run valgrind
        run: valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./target/debug/test-mem
        working-directory: rust

# Not my code
  publish_rust_to_nuget:
    runs-on: ubuntu-latest
    needs: [ pass ]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Push
        run: |
          cd rust/ffi/nuget
          mkdir runtimes && cd runtimes
          wget https://github.com/linksplatform/Data.Doublets/raw/binaries/windows-x64/native/Platform.Doublets.dll
          wget https://github.com/linksplatform/Data.Doublets/raw/binaries/macos-x64/native/libPlatform.Doublets.dylib
          wget https://github.com/linksplatform/Data.Doublets/raw/binaries/linux-x64/native/libPlatform.Doublets.so
          ls
          cd ..
          cd ../../../
          export REPOSITORY_NAME=$(basename ${{ github.repository }})
          wget "https://gist.githubusercontent.com/uselessgoddess/54e286dbda22935313615d65723e7670/raw/e98fe0073bf87f296786b543b8051d78f3144924/push-cpp-nuget.sh"
          CPP_PACKAGE_NUSPEC_PATH="rust/ffi/nuget/Platform.Data.Doublets.FFI.nuspec"
          echo "$CPP_PACKAGE_NUSPEC_PATH"
          echo "$CPP_PACKAGE_NUSPEC_PATH" > CPP_PACKAGE_NUSPEC_PATH.txt
          CPP_PACKAGE_VERSION="0.0.1"
          echo "$CPP_PACKAGE_VERSION"
          echo "$CPP_PACKAGE_VERSION" > CPP_PACKAGE_VERSION.txt
          bash ./push-cpp-nuget.sh